name: Bug Report
description: Report a bug in next-geo
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: next-geo version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: nextjs-version
    attributes:
      label: Next.js version
      placeholder: "15.0.0"
    validations:
      required: true

  - type: dropdown
    id: detection-method
    attributes:
      label: How is the LLM request detected?
      options:
        - Accept header (text/markdown)
        - URL suffix (.md)
        - User-Agent
        - Not sure
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Create a page.md with ...
        2. Run `curl -H "Accept: text/markdown" http://localhost:3000/...`
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Paste any error messages or logs. This will be rendered as code.
      render: shell
